### ISSUE TITLE
Explicitly set default permission settings when generating tmpFiles

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore-java#108]
Currently when a temp file is generated for data to be written into (and checksums to be calculated), we are using the default settings which relies on the JVM/system settings. This can potentially cause hashstore objects to be only accessible by a specific user (or specific group, which we made not want to add users to).

Hashstore objects should be group-readable so that we can set-up proper access control to external services (ex. `metadig`). 

**To Do:**
- Explicitly declare permission settings when generating temp files
- Example code to assist: https://github.com/NCEAS/metacat/blob/7fd6e53e89f88f0545c22181e354341beec63543/src/edu/ucsb/nceas/metacat/admin/SolrAdmin.java#L709

**Comment by artntek** [comment]
capturing our slack convo:

default file permissions should be `rw- r-- ---` or posix `640`

If setting these permissions on the temp file, please verify that these permissions also get transferred to the final location after the `mv`. Thanks!

**Comment by doulikecookiedough** [comment]
This has been completed via [Feature-108: Default Permissions on HashStore Objects](https://github.com/DataONEorg/hashstore-java/pull/109)
