### ISSUE TITLE
Refactor Hashstore to be an abstract class or interface

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore-java#14]
Discuss/review whether Hashstore should be an abstract class or interface and refactor the existing code.

To Do:
- Combine HashFileStore `put` and `putObject` (redundant)
- Combine HashFileStore and HashUtil classes (since HashUtil is not shared by any other classes)

**Comment by doulikecookiedough** [comment]
After further review, I believe `HashStore` should be an abstract class that implements an interface because there is default state present (depth, width, algorithm, etc.) that should remain constant and common shared behaviour (like the synchronization of sysmeta and object locks). An abstract class will also allow us to ensure that HashStore is instantiated correctly (it would not be appropriate to add logic or default behaviour into an interface). Additionally, any backend refactors/improvements will still have to follow the interface contract, so it remains flexible and swappable (since coupling is based on the contract).

**Comment by mbjones** [comment]
@doulikecookiedough it makes sense that `HashStore` shoudl be written to implement an interface, but at first glance I don't see why it should be `abstract` - if it is abstract, you can't instantiate it, and you would have to override it with another subclass. So, if you plan to make it abstract, what will override it, and what functionality do you think needs to be defaulted to the abstract class? Generally, abstract classes are used to provide common functionality used across multiple subclasses. I don't see the need for more than one HashStore-like class here, but maybe I am missing something key. Thanks.

**Comment by doulikecookiedough** [comment]
Thank you for the feedback @mbjones. I did not fully grasp the purpose of using an abstract class and came to a similar conclusion shortly after beginning my refactor (it was becoming overly complicated, and I was questioning why I was implementing an abstract class as I didn't need to provide any common functionality (the synchronization isn't something that needs to be shared). I initially thought that because I had default state, that alone was a good enough reason to implement an abstract class over just an interface - but it looks like I'm adding unnecessary complexity by doing so. I don't want to override HashStore with another class - so I will be moving forward with just an interface. You didn't miss anything, it was a misunderstanding on my part.

**Comment by doulikecookiedough** [comment]
Commented in the wrong issue, added conversation to correct issue here
---
Continuing our discussion from the respective PR for this issue:
>**Jing:** Is there any reason that HashFileStore can't implement the interface directly? To me, this HashStore is a real file HashStore. So I think maybe you might use HashFileStore to implements the interface directly.

> **Matthew:** I'm not sure about this. I think it is confusing if both `HashFileStore` and `HashStore` implement the interface - because it's not apparent which one a developer shold use (and so people might end up making calls directly to `HashFileStore`). 
> I'd rather see the permissions on `HashFileStore` be locked down from `public` to `protected`, so nobody else is tempted to use it directly.
> (Or are you saying we should eliminate `HashStore` altogether, and only have `HashFileStore`, which implements the interface?)

My thought process here is that if we were to swap our backends for HashStore, we wouldn't have to change anything in Metacat - but refactor `HashFileStore` instead with the relevant calls - or replace it entirely in `HashStore`. This way changes to the backend of our file storage system won't require any changes in Metacat. If we were to replace the backend, should we expect to overhaul the entire implementation of HashStore? In that case, we could consider combining HashStore and HashFileStore per Jing's suggestion. Or we could also have HashStore can extend `HashFileStore` while `HashFileStore` implements the HashStoreInterface?

@mbjones may we ask for your input?

**Comment by mbjones** [comment]
I could see it being done several ways (with and without an abstract class). In the simplest form, where we only have a single class implementing the storage system, I think we have:

```mermaid
classDiagram
    HashStore <|-- FileHashStore: implements
    <<Interface>> HashStore
    class HashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class FileHashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
```

In a slightly more complicated Factory pattern, we turn `HashStore` into an interface that is implemented by three types of store classes, and add a HashStoreFactory to generate one of these at runtime:

```mermaid
classDiagram
    HashStore <|-- FileHashStore: implements
    HashStore <|-- CephHashStore: implements
    HashStore <|-- S3HashStore: implements
    <<Interface>> HashStore
    class HashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class FileHashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class CephHashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class S3HashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class HashStoreFactory{
        +createHashStore(): HashStore
    }
```

Finally, if there is some common bit of implementation that could be shared across the implementing classes, such as a common set of utility functions or state management, then we could also introduce an abstract class to hold that:

```mermaid
classDiagram
    HashStore <|-- AbstractHashStore: implements
    AbstractHashStore <|-- FileHashStore: isa
    AbstractHashStore <|-- CephHashStore: isa
    AbstractHashStore <|-- S3HashStore: isa
    <<Interface>> HashStore
    class HashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    <<Abstract>> AbstractHashStore
    class AbstractHashStore{
      -commonStateVar
      -someUtility()
    }
    class FileHashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class CephHashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class S3HashStore{
      +store(pid, object)
      +retrieve(pid) Object
      +storeMetadata(pid, metadata)
      +retrieveMetadata(pid) SystemMetadata
      +delete(pid)
    }
    class HashStoreFactory{
        +createHashStore(): HashStore
    }
```

These are standard uses of standard design patterns, so no surprises here. We can start with the simplest case and expand downward as needed. Let's discuss next week.

**Comment by doulikecookiedough** [comment]
Thank you @mbjones for your feedback and help. We will move forward with the Factory pattern described and continue this conversation here: [https://github.com/DataONEorg/hashstore-java/issues/19](https://github.com/DataONEorg/hashstore-java/issues/19)
