### ISSUE TITLE
Move config file to well-known location to persist parameters across invocations

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore-java#24]
Upon initialization of `FileHashStore`, write a config file `hashstore.yaml` to `/etc/` with the loaded config values.

**To discuss before making this change:**
- Create a mermaid diagram (sequence diagram or flowchart) to illustrate process
- Review the process/diagram with backend team in which FileHashStore is invoked and how the mechanism ensures the correct configuration
- Where should the location of HashStore objects exist (ex. `/var/filehashstore/`)?
  - Is HashStore responsible for creating the folder? Or will this be done during the initial set-up/configuration process for Metacat

Matt's Feedback for Reference:
> As we discussed the other day, it will be important for an instantiated store to use the same config as previous ones (particularly the hash algorithm) -- so what if the config file were in a well-known location for the app (e.g., /etc/hashstore.yaml), and then it will persist across invocations. Startup of an instance would check the loaded config values against the extant store (e.g., ensuring that the depth, width, and algorithm all check out) before startup is enabled? If this were the case, then all HashStore constructors could take a yaml config file path as a param. Question -- would the factory be responsible for parsing this config file and passing the data to the store implementations?

**Comment by mbjones** [comment]
For your last Q on where should the store go, I think it should be configurable by the calling app (in this case, Metacat), and hashstore should be sure to initialize that storage space appropriately for its needs if it wasn't already initialized.

**Comment by doulikecookiedough** [comment]
Thank you for the quick response @mbjones. Regarding your question about whether the factory should be responsible for parsing this config file and passing the data to the store implementations - I think it should only be responsible for writing the `/etc/hashstore.yaml` file.

**Proposed flow:**
- Metacat calls HashStoreFactory `.getHashStore()`, which will check whether `etc/hashstore.yaml` exists.
  - If it does, `.getHashStore()` returns the desired HashStore object.
  - If it doesn't, `.getHashStore()` will read the default configuration from the properties file in `resources/HashStore.properties` and write the equivalent to `etc/hashstore.yaml`. 
- `.getHashStore()` returns the HashStore object (ex. FileHashStore) that instantiated with the properties found in `etc/hashstore.yaml`
   - `etc/hashstore.yaml` must always be present for HashStore objects to initialize

So HashStoreFactory reads/writes the configuration file if it's not present based on default/given values, but HashStore should parse the data itself to instantiate. I will bring this up for discussion during our next Arc Dev session to get feedback (or we can continue discussing here if you have scope to review).

**Note:** `getHashStore(String store_type)` requires the signature to be updated to `getHashStore(String store_type, Path store_path)` so that Metacat can configure the store path (and so that HashStore can initialize/create the required folders if they don't already exist).

**Diagram for Reference:**
```mermaid
sequenceDiagram
    Metacat->>+HashStoreFactory: .getHashStore("filehashstore", StorePath);
    HashStoreFactory->>-HashStoreFactory: loadProperties()
    alt hashstore.yaml: Exists
        HashStoreFactory->>+FileHashStore: FileHashStore(StorePath)
        note over FileHashStore: instantiate with hashstore.yaml values
        FileHashStore-->>-HashStoreFactory: FileHashStore
        HashStoreFactory-->>Metacat: HashStore
    else alt hashstore.yaml: Does Not Exist
        HashStoreFactory->>HashStoreFactory: configHashStore()
        note over  HashStoreFactory: Read from properties file and write to /etc/hashstore.yaml
        HashStoreFactory->>+FileHashStore: FileHashStore(StorePath)
        note over FileHashStore: instantiate with hashstore.yaml values
        FileHashStore-->>-HashStoreFactory: FileHashStore
        HashStoreFactory-->>Metacat: HashStore
    end
```

**Comment by doulikecookiedough** [comment]
**Proposed Flow:**
```mermaid
sequenceDiagram
    Metacat->>HashStoreFactory: .configureHashStore(storePath, dirDepth, dirWidth, algorithm, sysmetaNameSpace)
    HashStoreFactory->>+HashStoreFactory: setProperties()
    note over HashStoreFactory: default/other algorithm lists should not be changed through the interface
    alt etc/.hashstore.yaml: Exists
        rect rgb(191, 223, 255, 0.5)
        HashStoreFactory->>Metacat: Throw HashStoreConfigException("Config already exists")
        end
    else etc/.hashstore.yaml: Does Not Exist
        HashStoreFactory->>HashStoreFactory: initProperties()
        HashStoreFactory->>HashStoreFactory: writeConfig() --> etc/.hashstore.yaml
        note over HashStoreFactory: This ensures config file always present before creating HashStore
        HashStoreFactory-->>-Metacat: return True
    end
    Metacat->>HashStoreFactory: .getHashStore(classPackage);
    alt etc/.hashstore.yaml: Exists
        HashStoreFactory->>+FileHashStore: FileHashStore(StorePath)
        note over FileHashStore: instantiate with hashstore.yaml values
        FileHashStore-->>-HashStoreFactory: FileHashStore
        HashStoreFactory-->>Metacat: HashStore
    else alt etc/.hashstore.yaml: Does Not Exist
        rect rgb(191, 223, 255, 0.5)
        HashStoreFactory-->>Metacat: Throw HashStoreConfigException("HashStore not configured")
        end
    end
```

**Usage:**
```
// Configure Store, null values will be replaced with default property values
HashStoreFactory.configureHashStore("/metacat/filehashstore", null, null, null, "http://ns.dataone.org/service/types/v2.0")

// Get Store
HashStore myStore = HashStoreFactory.getHashStore("org.dataone.hashstore.filehashstore.FileHashStore")

// Use Store
myStore.storeObject(pid, inputStream)
```

**Notes & Assumptions:**
- Once a `HashStore` is configured, it cannot be changed
  - Allowing it to be changed introduces complex issues (ex. what to do with objects already stored with the existing config values? problematic when we have lots of objects)
  - The only items configurable are the: storePath, dirDepth, dirWidth, algorithm, sysmetaNameSpace
- If client tries to configure `HashStore`, if a `.hashstore.yaml` file is present it will throw an exception (config already exists)
- If client tries to get `HashStore` via factory method and `.hashstore.yaml` file is not found, it will throw an exception (`HashStore` not configured)
- There is a coupling between `HashStore` and `.hashstore.yaml`, and it must be configured once before `HashStore` can instantiate. This enforces a configuration to be present so that all `HashStore` implementations have a single source of truth.

I will experiment in Python first and return with findings.

**Comment by mbjones** [comment]
The path in the diagram `etc/.hashstore.yaml` seems unconventional. Can we simplify it to `/etc/hashstore.yaml` as the default? Or `/etc/hashstore.properties` in the Java case? Not sure which format would be better. And another alternative would be to store the config file at the root of the hashstore path, which would require always passing the path to `getHashStore()`. Let's discuss.

Also, we should discuss this `HashStoreFactory.configureHashStore()` method, as I'm worried about the disconnect with `getHashStore()`. I think it would be better to pass the parameters needed into a method like `getHashStore(String className, Properties config)`, and then the Factory can pass the properties to the FileHashStore constructor, which will check that it is in the right location, the store is consistent, etc. We could also have an explicit factory method:

```java
public HashStore getHashStore(String className) {
    return getHashStore(className, null);
}
```

In that case, if `config` is null, then getHashStore will assume it already exists and startup the exising HashStore, or throw an exception if it wasn't already configured. By doing it this way, there can be more than one store on disk, and the calling app determines their locations, which I think is appropriate. Let's discuss these potential pathways.

**Comment by doulikecookiedough** [comment]
Thank you for the quick feedback @mbjones! We can simplify the path to `/etc/hashstore.yaml` (or properties) - hiding the file was added so that we can proactively prevent it from being accidentally deleted.
- I am leaning towards switching to using `.properties` (so Python and Java libraries can "share" the same file)

**RE: `getHashStore(String className, Properties config)`**
- Your suggestion sounds more intuitive and less complicated. I did not really want to add the `configureHashStore()` method but was not completely sure how to proceed.
- I will explore this route instead and follow-up on Tuesday in our backend session.

**Comment by mbjones** [comment]
> proactively prevent it from being accidentally deleted

Hiding a file does not make it less likely to be deleted, it makes it more likely as people may not notice it before deleting the directory. We should rely on solid access controls and backup strategies to ensure its persistence.

**Comment by mbjones** [comment]
Oh, and if Java and Python are to share the same file, then yaml might be a more language-neutral format with good support in both languages.

**Comment by doulikecookiedough** [comment]
**Updated flow:**
```mermaid
sequenceDiagram
    Metacat->>HashStoreFactory: .getHashStore(String classPackage);
    HashStoreFactory->>HashStoreFactory: .getHashStore(String classPackage, Properties config)
    alt config != null
        HashStoreFactory->>+FileHashStore: HashStore store = FileHashStore(Properties config)
        alt etc/hashstore.yaml: Exists
            FileHashStore->>FileHashStore: loadProperties(etc/hashstore.yaml)
                note over FileHashStore: Confirm depth/width/storePath
            FileHashStore->>FileHashStore: validateConfig()
            alt hashstore.yaml does not match:
                rect rgb(191, 223, 255, 0.5)
                    FileHashStore-->>HashStoreFactory: Throw FileHashStoreConfigException()
                end
            else hashstore.yaml matches:
                rect rgb(0, 255, 0, 0.2)
                    FileHashStore-->>HashStoreFactory: return
                end
            end
        else etc/hashstore.yaml: Does Not Exist
            note over FileHashStore: Write etc/hashstore.yaml with values from `Properties config`
            FileHashStore->>FileHashStore: createConfigYaml()
            FileHashStore->>FileHashStore: Initialize private instance variables
            rect rgb(0, 255, 0, 0.2)
                FileHashStore-->>-HashStoreFactory: return
            end
        end
        rect rgb(0, 255, 0, 0.2)
            HashStoreFactory-->>Metacat: return store
        end
    else alt config == null
    note over HashStoreFactory: .getHashStore can be called without config, but throws exception if hashstore.yaml not found
        alt etc/hashstore.yaml: Exists
            HashStoreFactory->>+FileHashStore: HashStore store = FileHashStore()
            note over FileHashStore: FileHashStore initializes based on set config values since hashstore.yaml present
            note over FileHashStore: hashstore.yaml if found, should not be changed after set, so ready for direct init
            rect rgb(0, 255, 0, 0.2)
                FileHashStore-->>-HashStoreFactory: return
            end
            rect rgb(0, 255, 0, 0.2)
                HashStoreFactory-->>Metacat: return store
            end
        else etc/hashstore.yaml: Does Not Exist
            rect rgb(191, 223, 255, 0.5)
                HashStoreFactory-->>Metacat: Throw HashStoreConfigException("HashStore not configured. No properties found at /etc/hashstore.yaml")
            end
        end
    end
```

**Notes:**
- `FileHashStore` whether provided with a config or not, will always check whether a `etc/hashstore.yaml` exists.
    - If it does exist, it means that `HashStore` has been configured, and `FileHashStore` is ready to instantiate
    - If given a Properties object, it will validate the properties against the `etc/hashstore.yaml` file before returning
    - If it does not exist, it needs to be created.
        - `FileHashStore` will be responsible for writing the `etc/hashstore.yaml` when called to instantiate (and the file is not found).
- If factory method is called without a config (config is `null`), it will successfully return a `FileHashStore` as long as `etc/hashstore.yaml` exists. Otherwise, it will throw an exception: 
   - HashStoreConfigException("HashStore not configured. No properties found at: /etc/hashstore.yaml")

**Comment by artntek** [comment]
This looks good, with a couple of caveats:

1. Java handles `*.properties` files natively and easily, both for reading and instantiating a Properties object in memory (`props.load(reader)`) and for persisting the properties back to a file (`props.store(writer)`). If you decide to use `*.yaml`, you'll need to use a third-party library to parse and manipulate it into a usable form within your java code, and also to write it out to disk afterwards. I therefore recommend considering the trade-offs before deciding.

2. I *think* (but am not certain) that the properties are currently a mix of filehashstore-specific props (storepath, dir width, dir depth), and more-general "hashstore" props (which algorithms are supported, and which will be used). If so, I recommend making this distinction between the two categories when you refactor (They can still both live in the same place, but instead of everything having a key like `filehashstore.xxxxxx=`, only the props that are truly specific to filehashstore would look like this, and the the non-implementation-specific ones would be named something like `hashstore.xxxxxx=`).

**Comment by mbjones** [comment]
@artntek While I agree with your overall thoughts on java properties, one thing to note -- we plan to have both Metacat (Java) and MetaDIG (Python and Java and R) access the same hashstore. Given that, I was thinking that yaml would be a better cross-language format for this file, so that it can be read in all three. I think the java properties format is the least portable choice, with either yaml or JSON being a more portable alternative. Despite the need for a third party library. Many of our Java apps use JAX-RS, and so Jackson is a sensible choice in Java to read and write yaml and json. See https://stackabuse.com/reading-and-writing-yaml-files-in-java-with-jackson/

**Comment by doulikecookiedough** [comment]
Thank you @artntek and @mbjones for the feedback!

**RE: Configuration File Format**
- For python, I will continue with 'hashstore.yaml' for the time being and re-evaluate once I begin the java implementation.

**RE: Properties Distinction**
- The algorithm lists specifically will depend on the implementation - so I have renamed those lists to `FHS_DEFAULT_ALGO_LIST` and `FHS_OTHER_ALGO_LIST` in the `hashstore.yaml` to be written.
- I considered excluding it altogether (since it's implementation specific), but it may still be necessary so that other HashStores can match the support of the existing configuration (HashStores related to an organization are consistently set up).

After experimenting with the control flow proposed, it looks like it will be problematic when no config is provided. If the file store is extremely large, attempting to locate the `hashstore.yaml` file may lead to a poor user experience because `FileHashStore` will have to traverse all directories/files to find it. It may not pose an issue now, but can become a bottleneck later.

Additionally, when initializing `FileHashStore` or instantiating a `FileHashStore` at a later time for whatever reason, I feel that including a properties `config` object should actually be required in both cases.
- This will enforce the calling app to be aware of where they intend to store objects - and it will simplify the process to confirm/check for an existing configuration (so we know exactly where to look immediately, with the agreed assumption that `hashstore.yaml` should always be present in the root store path).
- By introducing/allowing a constructor for `FileHashStore` where properties can be "null", it adds a level of complexity that I don't feel is worth the time commitment to explore and flesh out (and is not necessary, since `FileHashStore` has to validate the `HashStore` configuration each time when the factory method is called to retrieve it anyway).
- I feel that it's better for us to be explicit here (requiring a `config` each time) to prevent confusion, reduce complexity and provide a smoother user experience.

Here is my new proposed flow:
```mermaid
sequenceDiagram
    Metacat->>HashStoreFactory: .getHashStore(String classPackage, Properties config)
    alt config != null
        HashStoreFactory->>+FileHashStore: HashStore store = FileHashStore(Properties config)
        FileHashStore->>FileHashStore: validateProperties(Properties config)
        note over FileHashStore: Get store_path from 'config'
        alt File hashstoreYaml = /[store_path]/hashstore.yaml: Exists
            FileHashStore->>FileHashStore: getProperties(hashstoreYaml)
                note over FileHashStore: Confirm depth/width/storePath
                note over FileHashStore: Confirm directory exists/objects found
            alt hashstore.yaml does not match:
                rect rgb(191, 223, 255, 0.5)
                    FileHashStore-->>HashStoreFactory: Throw FileHashStoreConfigException("Config - /[store_path]/hashstore.yaml' found but does not match given 'config'")
                end
            else hashstore.yaml matches:
                FileHashStore->>FileHashStore: instantiate with checked variables (depth, width, etc.)
                rect rgb(0, 255, 0, 0.2)
                    FileHashStore-->>HashStoreFactory: return
                end
            end
        else ./hashstore.yaml: Does Not Exist but HashStore Exists
            rect rgb(191, 223, 255, 0.5)
                FileHashStore-->>HashStoreFactory: Throw FileHashStoreConfigException("HashStore found but ./hashstore.yaml missing")
            end
        else /[store_root]/hashstore.yaml: Does Not Exist and HashStore Does Not Exist
            note over FileHashStore: config already has been validated at this point
            FileHashStore->>FileHashStore: initialize instance variables (depth, width, etc.)
            note over FileHashStore: Write etc/hashstore.yaml with values from `Properties config`
            FileHashStore->>FileHashStore: putProperties(Properties config)
            rect rgb(0, 255, 0, 0.2)
                FileHashStore-->>-HashStoreFactory: return
            end
        end
        rect rgb(0, 255, 0, 0.2)
            HashStoreFactory-->>Metacat: return store
        end
    else alt config == null
        rect rgb(191, 223, 255, 0.5)
            HashStoreFactory-->>Metacat: Throw HashStoreConfigException("HashStore configuration missing (Properties config).")
        end
    end
```

**Comment by doulikecookiedough** [comment]
While I implemented this flow in Python and it appeared to be working as intended, I discovered a bug during the Java implementation and subsequent testing.
- First, we check to see if the given store path + `/hashstore.yaml` exists:
    - If it does, we compare the values to ensure the config is the same, and raise exceptions if not.
    - If it doesn't, the code uses the given store path and iterates over any potential directories and files.
        - It only checks the given store path's location for said potential directories and files, so if a HashStore exists somewhere else in the server, it will not see it.
- As a result, it will write a new `hashstore.yaml` to the given store path **that is different from the existing HashStore**, splintering the store directories in two different locations.

Currently, I have two suggestions as to address this issue:
1) Write `hashstore.yaml` to two locations:
    - Current working directory of the app: (`System.getProperty("user.dir")`)
    - Object store directory
        - If we can't find `hashstore.yaml` with the given store path, we'll look in the current working directory.
        - If it's not there, it's not configured, and we proceed to initialize/instantiate with the given properties.
2) Write `hashstore.yaml` to a different location, the current working directory of the app.
    - We always look here to verify properties, and if it's not found, HashStore is not configured. No need to further walk over the file system.
    - We proceed with the next step.

Since HashStore is a library to be imported, the working directory can and will likely be different depending on the set-up of the calling app. So I am leaning towards writing in two locations. The calling app will always check for the expected location of `hashstore.yaml` in the object store directory - and fallback to the `hashstore.yaml` in the calling app's directory. Before initialization, it will always verify the supplied properties with the written properties from `hashstore.yaml`.

**Comment by mbjones** [comment]
@doulikecookiedough Here's a usecase to consider, and that we support on multiple VMs today, and should continue to support:

- Install multiple Metacat instances on the same VM, each with their own object store and data at different paths
For example:
    - ESA Metacat with data in directory `/var/esa`
        - Hashstore path: `/var/esa/hashstore`
    - GOA Metacat with data in directory `/var/goa`
        - Hashstore path: `/var/goa/hashstore`

**Comment by doulikecookiedough** [comment]
Since HashStore should be an atomic system, with minimal business logic, is it safe for me to assume that it is the calling app's responsibility to get the properties correct? And `HashStore`'s responsibility at this point is to verify the properties if a `hashstore.yaml` exists?

So when HashStore initializes, it will take the given properties' store path to check for `hashstore.yaml` and if it doesn't exist, we proceed to write it and initialize - disregarding that it could potentially be wrong. 

If it does exist, we confirm the properties given with the `hashstore.yaml` file found and raise an exception if it's different.

**Comment by mbjones** [comment]
That seems about right to me, but happy to discuss.

**Comment by doulikecookiedough** [comment]
@mbjones Awesome! Thank you for confirming. This would simplify the process quite a bit, so I am proceeding as discussed above 🙏.

**Comment by doulikecookiedough** [comment]
This issue is now addressed and merged into develop via [PR-25: Feature-24: FileHashStore Configuration ](https://github.com/DataONEorg/hashstore-java/pull/25)
