### ISSUE TITLE
Review/Refactor Module Structure

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore-java#40]
Currently, HashStore-java's modules are loosely structured and could be combined to improve clarity. Refactor HashStore-java by combining modules to keep a collection of related classes together where appropriate.

The project structure should appear similar, if not the same, to what follows:
```
/src/main/java/org/dataone/hashstore
|─ /exceptions
|─── ...
|─ HashStore.java
|─ FileHashStore.java
...
```

**Comment by mbjones** [comment]
Hi @doulikecookiedough -- our conversation this morning about module organization was about the python library and not the java library. The two languages organize classes within modules/packages very differently, and I think your current org.dataone.hashstore java package is quite reasonable. Our conversation was more about how to get the python modules into a similar structure given the file layout differences.  Before you make changes here in Java land, let's discuss what you think should be changed.

**Comment by doulikecookiedough** [comment]
Thank you for clarifying @mbjones and for the feedback. When I structured the python library I thought it was ok - but learned that about how to improve it this morning, so it led me to think that I may be not be following the best practices here in Java land too. When I get to this issue, I will review and discuss here before making any changes (or not making any).

**Comment by doulikecookiedough** [comment]
After reviewing other project examples, it does appear that the current structure is reasonable. The only concern I have now is that there are some methods that are duplicated/called in the `Client` class that can also be found in the `FileHashStore` class (not DRY). During testing, it also became apparent that a method to check whether a file exists in HashStore or not would be really useful when working with HashStore.

I will not make any changes to the structure and create new issues to:
1) Add a utility class that can be shared amongst HashStore-java members & to refactor affected classes
2) Confirm the addition of a new Public API method for "exists" in the next backend dev meeting (already mentioned once) along with reviewing the hashstore interface.
